<div class=razdel>
<div align=right><h3>RTF to HTML testing</h3></div>

<p>The problem of converting Word documents to HTML is rather acute, but the only possible way to parse Word files without using COM - is to parse RTF files. I'm often asked if it is possible to create good-looking HTML files from RTFs automatically. I've done some tests, and here is the result.</p>

<p>You can test the script by yourself, but mind, that it won't understand too complicated documents. Currently, only simple document formatting is supported: bold, italic, underlined text and font size. Documents having page numbers, headers, footers, images or any graphic elements - won't be parsed correctly.</p>

<p>Tables are not supported too, but may be I'll found a way to insert this feature.</p>

<p>Using the form below you can select any RTF file and view it in HTML format. If  you have any comments - you may contact me by <a href="mailto:paggard@paggard.com">e-mail</a>.</p>

<p><font color="#CC0000"><b>Warning!</b></font> If you're trying to test this script using the RTF, generated by my <a href="http://paggard.com/projects/rtf.generator/">RTF&nbsp;Generator</a> - it won't work - as RTF Generator creates very complicated documents for this test script, and the test document demonstrates almost all of the features.</p>


<h4>Stress test</h4>
<div class=code>
<form method=post enctype="multipart/form-data" action="gethtml.php" target=_blank>
<input type="file" name="rtffile[]" size=45 class=wide><br>
<input type="submit" value="Try the file" class=wide>
</form>
</div>

</div>
